{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "helm-guestbook.fullname" . }}-route
  labels:
    app: {{ template "helm-guestbook.name" . }}
    chart: {{ template "helm-guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- include .Values.route.labels | toYaml | nindent 4 }}
spec:
  host: {{ .Values.route.host }}.{{ .Values.route.ingressDomain }}
  to:
    kind: Service
    name: {{ template "helm-guestbook.fullname" . }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

  port:
    targetPort: 80
{{- end }}